export const AgeGroup = {
  AGE_20S: '20대',
  AGE_30S: '30대',
  AGE_40S: '40대',
  AGE_50S: '50대',
  AGE_60_PLUS: '60대 이상',
} as const;

export const Gender = {
  MALE: '남자',
  FEMALE: '여자',
} as const;

export const Religion = {
  NON_RELIGIOUS: '무교',
  CHRISTIANITY: '기독교',
  BUDDHISM: '불교',
  CATHOLICISM: '천주교',
  WON_BUDDHISM: '원불교',
  OTHER_RELIGION: '기타',
} as const;

export const Smoking = {
  NO_SMOKING: '비흡연',
  SOMETIMES: '가끔 흡연',
  EVERYDAY: '매일 흡연',
  E_CIGARETTE: '전자담배',
  TRYING_TO_QUIT: '금연중',
} as const;

export const Drinking = {
  NEVER: '전혀 안 마심',
  ONLY_IF_NEEDED: '필요할 때만 음주',
  SOMETIMES: '가끔 음주',
  OFTEN: '자주 음주',
  TRYING_TO_QUIT: '금주중',
} as const;

export const MBTI = {
  ISTJ: 'ISTJ',
  ISFJ: 'ISFJ',
  INFJ: 'INFJ',
  INTJ: 'INTJ',
  ISTP: 'ISTP',
  ISFP: 'ISFP',
  INFP: 'INFP',
  INTP: 'INTP',
  ESTP: 'ESTP',
  ESFP: 'ESFP',
  ENFP: 'ENFP',
  ENTP: 'ENTP',
  ESTJ: 'ESTJ',
  ESFJ: 'ESFJ',
  ENFJ: 'ENFJ',
  ENTJ: 'ENTJ',
  UNKNOWN: 'MBTI 모름',
} as const;

export const Personality = {
  CUTE: '아담한',
  RELIABLE: '듬직한',
  SMILES_OFTEN: '잘 웃는',
  DOESNT_SWEAR: '욕 안하는',
  NICE_VOICE: '목소리 좋은',
  TALKATIVE: '먼저 말 걸어주는',
  GOOD_LISTENER: '얘기를 잘 들어주는',
  ACTIVE: '활발한',
  QUIET: '조용한',
  PASSIONATE: '열정적인',
  CALM: '차분한',
  WITTY: '재치있는',
  POLITE: '예의 바른',
  SERIOUS: '진지한',
  UNIQUE: '엉뚱한',
  FREE_SPIRITED: '자유분방한',
  METICULOUS: '꼼꼼한',
  SENSITIVE: '섬세한',
  COOL: '쿨한',
  SINCERE: '성실한',
  LOYAL: '일편단심',
  OPEN_MINDED: '오픈마인드',
  AFFECTIONATE: '애정표현이 많은',
  CONSERVATIVE: '보수적인',
  CONSIDERATE: '배려심 있는',
  NEAT: '깔끔한',
  POSITIVE: '긍정적인',
  FRUGAL: '검소한',
  CHARACTERFUL: '개성있는',
  HONEST: '솔직한',
  PLAYFUL: '개구쟁이',
  DILIGENT: '부지런한',
  FAMILY_ORIENTED: '가정적인',
  COMPETENT: '능력있는',
  SELF_MANAGING: '자기관리 잘하는',
  RESPONSIVE: '연락 잘하는',
  WORKAHOLIC: '워커홀릭',
  SOCIABLE: '사교적인',
  LONER: '내향적인',
  COMPETITIVE: '승부욕 있는',
  EMPATHETIC: '정이 많은',
} as const;

export const PreferredPeople = {
  CUTE: '아담한',
  RELIABLE: '듬직한',
  SMILES_OFTEN: '잘 웃는',
  DOESNT_SWEAR: '욕 안하는',
  NICE_VOICE: '목소리 좋은',
  TALKATIVE: '먼저 말 걸어주는',
  GOOD_LISTENER: '얘기를 잘 들어주는',
  ACTIVE: '활발한',
  QUIET: '조용한',
  PASSIONATE: '열정적인',
  CALM: '차분한',
  WITTY: '재치있는',
  POLITE: '예의 바른',
  SERIOUS: '진지한',
  UNIQUE: '엉뚱한',
  FREE_SPIRITED: '자유분방한',
  METICULOUS: '꼼꼼한',
  SENSITIVE: '섬세한',
  COOL: '쿨한',
  SINCERE: '성실한',
  LOYAL: '일편단심',
  OPEN_MINDED: '오픈마인드',
  AFFECTIONATE: '애정표현이 많은',
  CONSERVATIVE: '보수적인',
  CONSIDERATE: '배려심 있는',
  NEAT: '깔끔한',
  POSITIVE: '긍정적인',
  FRUGAL: '검소한',
  CHARACTERFUL: '개성있는',
  HONEST: '솔직한',
  PLAYFUL: '개구쟁이',
  DILIGENT: '부지런한',
  FAMILY_ORIENTED: '가정적인',
  COMPETENT: '능력있는',
  SELF_MANAGING: '자기관리 잘하는',
  RESPONSIVE: '연락 잘하는',
  WORKAHOLIC: '워커홀릭',
  SOCIABLE: '사교적인',
  LONER: '내향적인',
  COMPETITIVE: '승부욕 있는',
  EMPATHETIC: '정이 많은',
} as const;

export const CurrentInterests = {
  MOVIES: '영화',
  NETFLIX: '넷플릭스',
  VARIETY_SHOWS: '예능',
  HOME_CAFE: '홈카페',
  CHATTING: '수다',
  DANCE: '댄스',
  SPACE_OUT: '멍때리기',
  COOKING: '요리',
  BAKING: '베이킹',
  DRAWING: '그림그리기',
  PLANT_PARENTING: '반려식물',
  INSTRUMENT: '악기연주',
  PHOTOGRAPHY: '사진찍기',
  FORTUNE_TELLING: '사주&타로',
  MAKEUP: '메이크업',
  NAIL_ART: '네일아트',
  INTERIOR: '인테리어',
  CLEANING: '청소',
  SCUBA_DIVING: '스쿠버다이빙',
  SKATEBOARDING: '스케이트보드',
  SNEAKER_COLLECTION: '신발수집',
  STOCKS: '주식',
  CRYPTO: '비트코인',
} as const;

export const FavoriteFoods = {
  TTEOKBOKKI: '떡볶이',
  MEXICAN: '멕시코 음식',
  CHINESE: '중식',
  JAPANESE: '일식',
  KOREAN: '한식',
  VEGETARIAN: '채식',
  MEAT_LOVER: '육식',
  FRUIT: '과일',
  WESTERN: '양식',
  STREET_FOOD: '스트릿 푸드',
  BAKERY: '제과류',
  HAMBURGER: '햄버거',
  PIZZA: '피자',
  BRUNCH: '브런치',
  ROOT_VEGETABLES: '구황작물',
  CHICKEN: '치킨',
  VIETNAMESE: '베트남 음식',
  SEAFOOD: '해산물',
  THAI: '태국 음식',
  SPICY_FOOD: '매운 음식',
} as const;

export const LikedSports = {
  BASEBALL: '야구',
  SOCCER: '축구',
  HIKING: '등산',
  RUNNING: '러닝',
  GOLF: '골프',
  GYM: '헬스',
  PILATES: '필라테스',
  HOME_TRAINING: '홈 트레이닝',
  CLIMBING: '클라이밍',
  CYCLING: '자전거',
  BOWLING: '볼링',
  BILLIARDS: '당구',
  YOGA: '요가',
  TENNIS: '테니스',
  SQUASH: '스쿼시',
  BADMINTON: '배드민턴',
  BASKETBALL: '농구',
  SURFING: '서핑',
  CROSSFIT: '크로스핏',
  VOLLEYBALL: '배구',
  PINGPONG: '탁구',
  FUTSAL: '풋살',
  FISHING: '낚시',
  SKI: '스키',
  BOXING: '복싱',
  SNOWBOARD: '스노우보드',
  SHOOTING: '사격',
  JIUJITSU: '주짓수',
  SWIMMING: '수영',
  MARATHON: '마라톤',
} as const;

export const Pets = {
  DOG: '강아지',
  CAT: '고양이',
  REPTILE: '파충류',
  AMPHIBIAN: '양서류',
  BIRD: '새',
  FISH: '물고기',
  LIKE_BUT_NOT_HAVE: '키우진 않지만 좋아함',
  HAMSTER: '햄스터',
  RABBIT: '토끼',
  NONE: '반려동물 없음',
  WANT_TO_HAVE: '키우고 싶음',
} as const;

export const SelfDevelopment = {
  READING: '독서',
  STUDYING: '공부',
  CAFE_STUDY: '카공',
  LICENSE_STUDY: '자격증 따기',
  LANGUAGE_LEARNING: '외국어 공부',
  INVESTING: '재테크',
  MIRACLE_MORNING: '미라클 모닝',
  CAREER_DEVELOPMENT: '커리어 개발',
  DIET: '다이어트',
  MINDFULNESS: '명상',
  LIFE_OPTIMIZATION: '목표지향적인',
  WRITING: '글쓰기',
} as const;

export const Hobbies = {
  GAMING: '게임',
  MUSIC: '음악',
  OUTDOOR: '야외활동',
  MOVIES: '영화',
  DRAMA: '드라마',
  CHATTING: '수다',
  SPACE_OUT: '멍때리기',
  APPRECIATION: '감상',
  DANCE: '댄스',
  COOKING: '요리',
  BAKING: '베이킹',
  DRAWING: '그림',
  PLANT_CARE: '식물 가꾸기',
  INSTRUMENT: '악기 연주',
  PHOTOGRAPHY: '사진 찍기',
  WEBTOON: '웹툰',
  MAKEUP: '메이크업',
  INTERIOR: '인테리어',
  CLEANING: '청소',
  SCUBA_DIVING: '스쿠버다이빙',
  COLLECTING: '수집',
  STOCKS: '주식',
} as const;
